main: pk.ajneb97.PlayerKits2
version: 0.0.2
name: PlayerKits2
api-version: 1.13
softdepend: [Vault,PlaceholderAPI]
author: [Ajneb97, Infnox]

commands:
  kit:
    description: Main command of PlayerKits2
    aliases: [kits,playerkits]